/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package games;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/**
 *
 * @author admin
 */
public class Tik_tok extends javax.swing.JFrame {
public int tk=0;
    
        
     Timer t=new Timer(10,new ActionListener()
        {
            public void actionPerformed(ActionEvent e){
               /* 
                if(kln==-105 || kln==-2431 || kln==-12673 || kln==-627 || kln==-1495 || kln==-3451 || kln==-1131 || kln==-1729){
                    System.out.println("tick wins");
                    JOptionPane.showMessageDialog(null,player1+" wins");
                    System.exit(0);
                } 
                if(ln==105 || ln==2431 || ln==12673 || ln==627 || ln==1495 || ln==3451 || ln==1131 || ln==1729){
                    
                    
                        System.out.println("Cross wins");
                    JOptionPane.showMessageDialog(null,Player2+" wins");
                    System.exit(0);
                }*/
                
               
               if(ln=="1" && kln=="1" && lln=="1" || pln=="1" && qln=="1" && rln=="1" || mln=="1" && nln=="1" && oln=="1" ||
                       ln=="1" && mln=="1" && pln=="1" || kln=="1" && qln=="1" && nln=="1" || lln=="1" && rln=="1" && oln=="1"
                            ||ln=="1" && nln=="1" && rln=="1" || lln=="1" && nln=="1" && pln=="1" ){
                    System.out.println("tick wins");
                    JOptionPane.showMessageDialog(null,player1+" wins");
                    System.exit(0);
               }
               else if(ln=="o" && kln=="o" && lln=="o" || pln=="o" && qln=="o" && rln=="o" || mln=="o" && nln=="o" && oln=="o" ||
                       ln=="o" && mln=="o" && pln=="o" || kln=="o" && qln=="o" && nln=="o" || lln=="o" && rln=="o" && oln=="o"
                            ||ln=="o" && nln=="o" && rln=="o" || lln=="o" && nln=="o" && pln=="o" ){   
                        System.out.println("Cross wins");
                    JOptionPane.showMessageDialog(null,Player2+" wins");
                    System.exit(0);
                   
               }
               
                
               
               
                if(msclc==9){
                    System.out.println("findsih");
                    msclc=-1;
                    tk++;
                    
                    
                    if(tk==10){
                        System.exit(0);
                    }
                        
                }
                
    }
        }
                );
 
    
    /**
     * Creates new form Tik_tok
     */
    public Tik_tok() {
        initComponents();
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        c8 = new javax.swing.JLabel();
        c9 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(903, 703));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c2MouseClicked(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(320, 20, 240, 190);

        c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c3MouseClicked(evt);
            }
        });
        getContentPane().add(c3);
        c3.setBounds(570, 20, 190, 190);

        c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c4MouseClicked(evt);
            }
        });
        getContentPane().add(c4);
        c4.setBounds(130, 220, 180, 240);

        c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c5MouseClicked(evt);
            }
        });
        getContentPane().add(c5);
        c5.setBounds(320, 220, 240, 240);

        c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c6MouseClicked(evt);
            }
        });
        getContentPane().add(c6);
        c6.setBounds(570, 220, 200, 240);

        c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c7MouseClicked(evt);
            }
        });
        getContentPane().add(c7);
        c7.setBounds(130, 470, 180, 200);

        c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c8MouseClicked(evt);
            }
        });
        getContentPane().add(c8);
        c8.setBounds(320, 470, 240, 200);

        c9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c9MouseClicked(evt);
            }
        });
        getContentPane().add(c9);
        c9.setBounds(570, 470, 190, 200);

        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1MouseClicked(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(130, 20, 180, 190);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 904, 713);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int odd=1,even=1,msclc=0;//ln=1,kln=1;
String ln,kln,lln,mln,nln,oln,pln,qln,rln;
String player1=JOptionPane.showInputDialog("enter the first player name");
String Player2=JOptionPane.showInputDialog("enter the second player name");
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        //msclc++;
        System.out.println(msclc);
        
// TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked
int a=0;
    private void c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseClicked
if(msclc==0){
    c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
}

if( a==0){
    a++;
    msclc++;
    System.out.println("yes mouse is succesfully working "+msclc);
}

if( msclc>0 && msclc%2==0){
  //  c1.setIcon(cross.png);
    //c1.setImage(new ImageIcon("cross.png"));
    c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/cross.png")));
    ln="0";
}else{
    c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/tick.png")));
    ln="1";
}


        // TODO add your handling code here:
    }//GEN-LAST:event_c1MouseClicked
int b=0;
    private void c2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseClicked

        
if(b==0){
    b++;
    msclc++;
    System.out.println("yes mouse is succesfully working "+msclc);
}
if(msclc>0 && msclc%2==0){
  //  c1.setIcon(cross.png);
    //c1.setImage(new ImageIcon("cross.png"));
    c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/cross.png")));
    kln="0";
}else{
    c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/tick.png")));
    kln="1";
}
// TODO add your handling code here:
    }//GEN-LAST:event_c2MouseClicked
int c=0;
    private void c3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3MouseClicked


if(c==0){
    c++;
    msclc++;
    System.out.println("yes mouse is succesfully working "+msclc);
}

if(msclc>0 && msclc%2==0){
  //  c1.setIcon(cross.png);
    //c1.setImage(new ImageIcon("cross.png"));
    c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/cross.png")));
    lln="0";
}else{
    c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/tick.png")));
    lln="1";
}
// TODO add your handling code here:
    }//GEN-LAST:event_c3MouseClicked
//msclc=msclc+k;
    int d=0;
    private void c4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c4MouseClicked

if(d==0){
    d++;
    msclc++;
    System.out.println("yes mouse is succesfully working "+msclc);
}   // TODO add your handling code here:

if(msclc>0 && msclc%2==0){
  //  c1.setIcon(cross.png);
    //c1.setImage(new ImageIcon("cross.png"));
    c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/cross.png")));
    mln="0";
}else{
    c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/tick.png")));
    mln="1";
}
    }//GEN-LAST:event_c4MouseClicked
int e=0;
    private void c5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c5MouseClicked

if(e==0){
    e++;
    msclc++;
    System.out.println("yes mouse is succesfully working "+msclc);
}   // TODO add your handling code here:

if(msclc>0 && msclc%2==0){
  //  c1.setIcon(cross.png);
    //c1.setImage(new ImageIcon("cross.png"));
    c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/cross.png")));
    nln="0";
}else{
    c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/tick.png")));
    nln="1";
}
    }//GEN-LAST:event_c5MouseClicked
int f=0;
    private void c6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c6MouseClicked

if(f==0){
    f++;
    msclc++;
    System.out.println("yes mouse is succesfully working "+msclc);
}

if(msclc>0 && msclc%2==0){
  //  c1.setIcon(cross.png);
    //c1.setImage(new ImageIcon("cross.png"));
    c6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/cross.png")));
    oln="0";
}else{
    c6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/tick.png")));
    oln="1";
}
       }//GEN-LAST:event_c6MouseClicked
int g=0;
    private void c7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c7MouseClicked

if(g==0){
    g++;
    msclc++;
    System.out.println("yes mouse is succesfully working "+msclc);
}   

if(msclc>0 && msclc%2==0){
  //  c1.setIcon(cross.png);
    //c1.setImage(new ImageIcon("cross.png"));
    c7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/cross.png")));
    pln="0";
}else{
    c7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/tick.png")));
    pln="1";
}

    }//GEN-LAST:event_c7MouseClicked
int h=0;
    private void c8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c8MouseClicked

if(h==0){
    h++;
    msclc++;
    System.out.println("yes mouse is succesfully working "+msclc);
}   
if(msclc>0 && msclc%2==0){
  //  c1.setIcon(cross.png);
    //c1.setImage(new ImageIcon("cross.png"));
    c8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/cross.png")));
    qln="0";
}else{
    c8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/tick.png")));
    qln="1";
}
    }//GEN-LAST:event_c8MouseClicked
int i=0;
    private void c9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c9MouseClicked

if(i==0){
   i++;
    msclc++;
    System.out.println("yes mouse is succesfully working "+msclc);
}   
if(msclc>0 && msclc%2==0){
  //  c1.setIcon(cross.png);
    //c1.setImage(new ImageIcon("cross.png"));
    c9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/cross.png")));
    rln="0";
}else{
    c9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/games/tick.png")));
    rln="1";
}
    }//GEN-LAST:event_c9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tik_tok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tik_tok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tik_tok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tik_tok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tik_tok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel c9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
